### ISSUE TITLE
Animeset cog issue

### ISSUE THREAD

**Issue by pieruru** [Redjumpman/Jumper-Cogs#13]
There is a credential issue going on with it. I typed my username and password correctly and its staying its not right. I went and made a new one to see if its an issue with my account and still not working. Unloading and reloading the cog doesnt seem to help either. But thank you for taking the time to look over on the issue.

**Comment by Ravarath** [comment]
I'd like to second this issue, all of a sudden the cog's credentials don't work. Can't ping for anything so I just disabled it until this gets updated, thanks for looking into it.

**Comment by Redjumpman** [comment]
Will be fixed by this Friday. Already know the fix, I'll comment here again once the fix has been applied. Thank you for your patience and for reporting this issue.

**Comment by Redjumpman** [comment]
This issue has now been fixed. Please update this cog and reload it.
