### ISSUE TITLE
Pokedex no longer showing pokemon images

### ISSUE THREAD

**Issue by pwnulatr** [Redjumpman/Jumper-Cogs#15]
When using `[p]pokedex pokemon <whatevername>` it returns the correct dex info, but the image link shows up as `https://img.pokemondb.net/s.png`. There are no errors in red.log or the CMD window to report.

**Comment by Redjumpman** [comment]
Have you updated tot he latest version? Also please join this server and post inquiries in that channel before making an issue. Someone might already have a resolution. https://discord.gg/c6HQUb7

**Comment by Redjumpman** [comment]
Might be an issue only with certain pokemon from sun and moon. Investigating the issue.

**Comment by Redjumpman** [comment]
This error should be fixed in the current update, I'll leave this PR open for a few days to ensure this bug has been smashed.

**Comment by Redjumpman** [comment]
This seems fixed now.
