### ISSUE TITLE
[shop] "gift" command

### ISSUE THREAD

**Issue by Zylvian** [Redjumpman/Jumper-Cogs#150]
Lots of times, me and other users have wanted to simply give items to other users from our own inventory, but the only way to do this currently is by using the trade command, and then you have to give something in return. 

There should be a user friendly way to simply give each other items for free, and that's what the "gift" command should do.

_[p] shop **gift** [user] [quantity] [item]_

Seems easy enough to implement by removing bits and bobs from trade.

**Comment by Redjumpman** [comment]
This is pretty easy to do. My V2 had this. I'll add it back since it seems some people like it.

**Comment by Redjumpman** [comment]
Added as of Shop 3.1 #152
