### ISSUE TITLE
Turtle Races for Red Version 3

### ISSUE THREAD

**Issue by SlamBerrySlam** [Redjumpman/Jumper-Cogs#151]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Turtle Races
Version: 🤷🏾‍♀️

# Feature Description
*Please include the motivation / use case for this feature.*
Please update the turtle racing cog for Red’s updated version 3. The old one will not work and it was one of the most fun things to do in Red bot.

# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:** 
.race start

**Expected result:**
Races started and invited other users for join 

**Steps to reproduce:**

**Please tell me about your environment/OS:**

**Comment by Redjumpman** [comment]
Done. Try out Race in V3!
