### ISSUE TITLE
russianroulette.py cog not being able to load due to syntax error

### ISSUE THREAD

**Issue by Catacalys** [Redjumpman/Jumper-Cogs#157]
For some reason, I am unable to install your russianroulette code due to a syntax error as follows:

```
        File "N:\redbot\cogs\russianroulette.py", line 7, in <module>
    from .kill import outputs
ImportError: No module named "cogs.kill"
```

I tried updating discord.py, but it didn't work. any help?

**Comment by ASSASSIN0831** [comment]
Use the v2 version, add the repo as https://github.com/Redjumpman/Jumper-Plugins@master

**Comment by seM-han** [comment]
Thanks!
