### ISSUE TITLE
Syntax error: Raffle cog [Unsolved.]

### ISSUE THREAD

**Issue by Catacalys** [Redjumpman/Jumper-Cogs#158]
I tried to install the cog, but there is a syntax error, but no explanation.

```
File "Q:\redbot\cogs\raffle.py", line 50
    await ctx.send(f"You are running raffle version {__version__}")

SyntaxError: invalid syntax
```

**Comment by seM-han** [comment]
![s](https://user-images.githubusercontent.com/40187061/46889100-90ecf300-ce30-11e8-9144-53c99b9c0a53.png)

there's also a ^ under the " next to `{__version__}`.

Does it have to do with the "`f`" next to the string that reminds you of the version?

**Comment by seM-han** [comment]
I asked in discord, as nobody's helped here.
