### ISSUE TITLE
Raffle Request

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Redjumpman/Jumper-Cogs#159]
The ability to add a message (from DM's), to the raffle, which then gets sent to the winner, so if it's steam games or something with a code, the code can be automatically DM'd to the winner when the raffle finishes.

**Comment by Redjumpman** [comment]
This is probably a good idea. Only thing that could be annoying is if the user has DMs turned off. What do you propose should happen in those cases?

**Comment by Ianardo-DiCaprio** [comment]
Is there a way to know that it failed to send? If so you could make it so that if it fails it sends a message to the raffle author saying that it didn't send

**Comment by Redjumpman** [comment]
Yeah there are ways to check for that. I haven't committed to adding this feature yet though.
