### ISSUE TITLE
[Shop V3] shop order broken

### ISSUE THREAD

**Issue by Colean128** [Redjumpman/Jumper-Cogs#160]
Note: for support questions, please use the Cog Support Server. This repository's issues are reserved for feature requests and bug reports.

I'm submitting a ...

bug report

Cog Information

Name: Shop
Version: 3.1.04

Bug Report

Screenshot of console: (If Applicable)
Not applicable

Command used:
[p]shop buy

Expected result:
It would buy Monopoly

Actual result:
It bought Ludo

Steps to reproduce:
IDK
I think it might be something to do with the alphabetical order and shop order not being synced
https://cdn.discordapp.com/attachments/475594153338863616/516006471436075009/help.gif

Please tell me about your environment/OS:
I use Windows 10.
The bot runs on an WSL Ubuntu 18.04 enviroment

**Comment by Redjumpman** [comment]
Fixed in 3.1.05 df05bb2a4bf3f2c2586db66c626aeef493a4208b
