### ISSUE TITLE
[RUSSIAN ROULETTE V2] first time the command is run, it says "an active game is happening"

### ISSUE THREAD

**Issue by Catacalys** [Redjumpman/Jumper-Cogs#161]
It was working fine at first, but then it started to do something peculiar: every time my bot turns on, i need to reset the russian roulette system. It is not something bot-breaking, but it is an annoyance. I've tried reinstalling the cog, since i've edited it to flavor for something me and my friends would enjoy. Any help would be appreciated.

**Comment by Redjumpman** [comment]
I'm not longer maintaining anything on my v2 repository.
