### ISSUE TITLE
Level 5 heist issue.

### ISSUE THREAD

**Issue by pieruru** [Redjumpman/Jumper-Cogs#17]
https://gyazo.com/69daccfe00410e75852ab8e028808e86 its giving me  that issue with bank level 5 in heist again. I unloaded and reloaded the command and tried again same issue.

**Comment by Redjumpman** [comment]
"Again". What is your discord username? Sorry this issue keeps coming back to haunt me. Can you try updating to the latest version of heist? If it still happens can you post your full console error for me to review?

**Comment by pieruru** [comment]
Oh its 0111000, but how do i go about that? I think i unloaded and reloaded the heist module and same error, now with the level 4 heist that is normal, its just always the level 5 gives me that error. Im not hosting the bot so i have to ask Caleb for the console error, unless there is a way to get that thru filezilla or putty cuz thats what I have to access it but clueless on finding it o.O

**Comment by Redjumpman** [comment]
Update to heist 2.0
