### ISSUE TITLE
[Raffle] Nonetype error

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Redjumpman/Jumper-Cogs#175]
When I start my bot I get "'NoneType' object has no attribute 'id'" in console, after trial and error of loading with different cogs I have found that it's raffle that is causing it.

**Comment by Flame442** [comment]
Can you post the actual error please? It helps to know what file and line is causing the errors, and the traceback the bot provides will have that information.

**Comment by Ianardo-DiCaprio** [comment]
`'NoneType' object has no attribute 'id'` is the only thing that shows in console, I found it was raffle by unloading cogs to see when it came or went.

**Comment by Ianardo-DiCaprio** [comment]
Turns out it was something in the raffles settings.json and deleting it fixed it
.
