### ISSUE TITLE
Error loading casino into latest version of red!

### ISSUE THREAD

**Issue by xXxCake2019xXx** [Redjumpman/Jumper-Cogs#176]
[https://cakegaming.net/screenshots/5XmwVmKdI.png](url) <- screenshot of errors.

I add the repo, i install the casino cog. Then when i go to load it. it errors.

**Comment by xXxCake2019xXx** [comment]
btw this is for the latest build of red that just updated.

**Comment by Ianardo-DiCaprio** [comment]
If you are senpaibrad on Discord from the errors you need to pip install casino. If you're not, please update the screenshot as it doesn't open.

**Comment by aikaterna** [comment]
Closing this as your screenshot is not available any more and it's been a few months since you've replied. Please open an issue with a text traceback if you have more issues.
