### ISSUE TITLE
Suggestions to improve raffle

### ISSUE THREAD

**Issue by Yandols** [Redjumpman/Jumper-Cogs#18]
There should be a settable limit to the amount of tickets one can buy for raffle, or a mode where only 1 ticket can be bought per person.

I was trying to use raffle to make a steam key giveaway and told my members to use `!raffle buy 1` to join then a rebel used `!raffle buy 69`, which automatically makes said user a winner aka rigged raffle.

Also in the case of where only 1 ticket can be bought per person mode, `!raffle buy` should default to buying 1 ticket instead of displaying the help text for how many tickets to buy.

**Comment by Redjumpman** [comment]
How would buying 1 raffle be different then hosting a lottery? I guess if you want everyone to a pay a fee I can understand. I will look into adding a one-shot mode. In the mean time I recommend using lottery.

**Comment by skeith** [comment]
The current ticket max option is able to do this, @Redjumpman

**Comment by Redjumpman** [comment]
Oh man. You are right! @Yandols try the latest update and setting the ticket max to 1.

**Comment by Yandols** [comment]
That's odd, that update was 14 hours ago but I installed raffle just under 3 hours ago, and I didn't get an option to set maximum tickets. Outdated red cache maybe? In any case that solves my problems. Thanks!

**Comment by Redjumpman** [comment]
Probably the issue. Ill try to add versioning in the future to help.

**Comment by Yandols** [comment]
You should still also consider my last suggestion where I said `!raffle buy` should default to buying 1 ticket when the max tickets allowed is set to 1.
