### ISSUE TITLE
[Raffle] Getting an error when starting a raffle with the bot.

### ISSUE THREAD

**Issue by HenrickTheBull** [Redjumpman/Jumper-Cogs#183]
> Exception in command 'raffle start'
> Traceback (most recent call last):
>   File "/home/henrick/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "/home/henrick/.local/share/Red-DiscordBot/cogs/CogManager/cogs/raffle/raffle.py", line 86, in start
>     embed = discord.Embed(description=description, title=title, color=self.bot.color)
>   File "/home/henrick/.local/lib/python3.7/site-packages/redbot/core/bot.py", line 176, in color
>     raise AttributeError("Please fetch the embed color with `get_embed_color`")
> AttributeError: Please fetch the embed color with `get_embed_color`
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/henrick/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
>     await ctx.command.invoke(ctx)
>   File "/home/henrick/.local/lib/python3.7/site-packages/redbot/core/commands/commands.py", line 582, in invoke
>     await super().invoke(ctx)
>   File "/home/henrick/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1158, in invoke
>     await ctx.invoked_subcommand.invoke(ctx)
>   File "/home/henrick/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "/home/henrick/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: Please fetch the embed color with `get_embed_color``
> 

I get this error everytime I try to start a raffle regardless of what settings I pass to it.

**Comment by Flame442** [comment]
It looks like you are currently using the dev build of red, rather than the stable build. If so, you cannot expect all cogs to work as the current dev build includes breaking changes.

**Comment by aikaterna** [comment]
This was resolved in 696b9b1.
