### ISSUE TITLE
animelist: returns wrong link & picture

### ISSUE THREAD

**Issue by GhostSquad57** [Redjumpman/Jumper-Cogs#19]
Using the 'manga' command to find manga only sort of works:

It returns the proper description, but the link and the preview picture is actually wrong.

Here's a picture of the issue:
![2016-12-06_1300x637](https://cloud.githubusercontent.com/assets/1379876/20947184/111661ba-bbdc-11e6-8be4-b2a7764ba8ac.jpg)

This appears to happen every time calling the 'manga' command

**Comment by GhostSquad57** [comment]
the link returns /anime/NUMBER instead of /**manga**/NUMBER

**Comment by Redjumpman** [comment]
Animelist has just been updated and now uses embeds. I will later have a feature that allows you to toggle embed or legacy in the future, but as of now this error no longer exists and so I will close this PR.

**Comment by GhostSquad57** [comment]
I just update the cog and the error is still present

**Comment by GhostSquad57** [comment]
Well actually, only part of the error is still present.

Information is now correct, but the link provided by "All the information you need about" is still wrong.

Using "manga berserk" outputs information about the manga, but the link points "https://myanimelist.net/anime/2" instead of "https://myanimelist.net/manga/2"

**Comment by Redjumpman** [comment]
Try the new update I just posted. I found the reason. Sorry :/

**Comment by GhostSquad57** [comment]
It works now!

Thanks for fixing it man :+1:
