### ISSUE TITLE
[SHOP] Many thing broken.

### ISSUE THREAD

**Issue by llek100** [Redjumpman/Jumper-Cogs#197]
Hi, I am using your shop cog for economy on my server. But there are many things wrong. The next, back and prev doesn't work in menus. Next works but only sometimes. Inventory is completely broken next, prev, back does not work at all. And you have stated that redeem works for multiple items at once but.. it doesn't. I know that it is very hard to maintain multiple cogs for basically free. I would donate but I did not see any donation link. I would pay for you to fix this. Thank you for everything.

**Comment by aikaterna** [comment]
The latest commit should have addressed everything here except for your comment about redeeming multiple items. I will leave this open as a reminder to look at that point at a future time.

**Comment by aikaterna** [comment]
Would be great if I didn't fat finger the close button on mobile too...

**Comment by aikaterna** [comment]
I looked into the statement of "And you have stated that redeem works for multiple items at once but.. it doesn't." It seems on the shop wiki RJM has said "You can redeem multiple items." which is true, just not all at once through one use of the command. So I am leaving this comment that it seems to work as intended. You can use the shop redeem command multiple times to redeem multiple items - one at a time.
