### ISSUE TITLE
[RAFFLE]: Choosing 10 or 20 winners will draw 1 or 2 respectively

### ISSUE THREAD

**Issue by ghost** [Redjumpman/Jumper-Cogs#199]
I don't really know what else to provide other than an image of the failure below.
![image](https://user-images.githubusercontent.com/55517257/84916547-1f118600-b0b6-11ea-9726-b661eb89cb8c.png)
In this instance all 20 people should have been drawn but only 2 were. The same happens for 10 people and it drawing 1. Almost like it doesnt handle the 0 as it can do 9, 11 & 19, 21.
I have installed red locally and experienced the same thing so I am unsure of what else to try.
I am available here or on the discord in your channel in the Red Cogs Server.

Any info or insight is appreciated.

OJ

**Comment by Drapersniper** [comment]
> I don't really know what else to provide other than an image of the failure below.
> ![image](https://user-images.githubusercontent.com/55517257/84916547-1f118600-b0b6-11ea-9726-b661eb89cb8c.png)
> In this instance all 20 people should have been drawn but only 2 were. The same happens for 10 people and it drawing 1. Almost like it doesnt handle the 0 as it can do 9, 11 & 19, 21.
> I have installed red locally and experienced the same thing so I am unsure of what else to try.
> I am available here or on the discord in your channel in the Red Cogs Server.
> 
> Any info or insight is appreciated.
> 
> OJ

The code specifically only allows you to set a maximum of 9 winners (a single digit). It currently works as designed, although it could be useful to make that clearer to the user, or only allow them to set something less than 10.

**Comment by ghost** [comment]
Ah, many thanks, I will put in a feature request shortly.
Appreciate it.
