### ISSUE TITLE
HTTP error 400 when using <p>shop redeem

### ISSUE THREAD

**Issue by A-Chewy-1** [Redjumpman/Jumper-Cogs#20]
Command functions as expected, but on execution the following error is thrown to the channel the command was issued from:

Error in command 'shop redeem' - HTTPException: BAD REQUEST (status code: 400): Cannot send messages to this user

**Comment by Redjumpman** [comment]
Thanks for posting. Ill be investigating soon.

**Comment by Aioxas** [comment]
Is the bot trying to PM you? If so, you gotta go to umm privacy settings and uncheck no dm from strangers option

**Comment by A-Chewy-1** [comment]
discord is hiding the privacy settings from me :/

The user's are getting the PM, but its throwing the error to channel as well.

**Comment by A-Chewy-1** [comment]
I had the notify role set on the bot as well, this was causing the error.
