### ISSUE TITLE
[Race] Bet deposit after finish

### ISSUE THREAD

**Issue by Lucasark** [Redjumpman/Jumper-Cogs#214]
After finish race, bet is not considerated.

Example:
![image](https://user-images.githubusercontent.com/31750882/93717475-79563300-fb4c-11ea-9fd8-ec33d828f2c6.png)
![image](https://user-images.githubusercontent.com/31750882/93717459-69d6ea00-fb4c-11ea-8fac-e07634a5491a.png)

I started race, and have only me and bot.
I bet 150 on me. (My new balance is 4600)
~Race started and I won

Prize pool is 250, and multiplayer is 2.0.

So, my new balance shoud be 5150 (prize[250]+bet[150*2]=550+[old balance]4600=5150.
But It only deposite 25(prize pool) and didnt considerated bet, made my new balance 4850.

**Comment by aikaterna** [comment]
Hello, I have finally had time to look into your issue as I'm working on Race today. You have set the "Players needed for payout" to 1. What this means is that there needs to be another human player in your game besides yourself for it to pay out. The other player in your game in your pics was your bot. So if you'd like the game to pay out when it's just one person playing vs. the bot, set the players needed for payout to 0. There is some help text regarding this condition in [p]setrace payoutmin but I am going to make it a little more explicit in the next version of the cog.
