### ISSUE TITLE
[CASINO] Can start memdesigner multipletimes

### ISSUE THREAD

**Issue by Brandjuh** [Redjumpman/Jumper-Cogs#220]
People are able to start multiple times the memdesigner. I would like to see that this is not possible.

![image](https://user-images.githubusercontent.com/26203955/99157820-c2e67880-26cc-11eb-9000-b971394533df.png)
![image](https://user-images.githubusercontent.com/26203955/99157863-135dd600-26cd-11eb-9ce1-ca85b7f5bbf4.png)

**Comment by aikaterna** [comment]
c1ecd9a
