### ISSUE TITLE
[Raffle] Days issue when setting up a raffle

### ISSUE THREAD

**Issue by Menteroth** [Redjumpman/Jumper-Cogs#227]
It seems like using days when setting up a raffle doesn't want to work. It accepts the input but raffle instantly ends when it's posted.

**Comment by aikaterna** [comment]
Is this days for the timer or the "days on server" requirement? I have done some preliminary testing on both and the raffle was behaving as expected.

**Comment by Menteroth** [comment]
This is what I tried. It was instantly finished the same second the command was invoked.
`raffle start 7 days XBOX Game Pass for PC.` 

I had to use this instead to get 7 days.
`raffle start 168:00:00 XBOX Game Pass for PC.`

Not sure why I didn't put this info in the issue to begin with. Sorry about that.

**Comment by aikaterna** [comment]
You must use a number like 168:00:00 as the parser does not support natural language like "7 days" - this is described in the command help for raffle.

**Comment by Menteroth** [comment]
I guess I read too fast. I thought this was showing you could type like that too.
![image](https://user-images.githubusercontent.com/24851042/103181205-18529f80-489f-11eb-8205-b4904456eac2.png)

**Comment by aikaterna** [comment]
No, that is just an example of the format to use for different qualifiers: days, hours, minutes, seconds being in the 00:00:00:00 format or how it would parse with lesser slots like 00:00.

**Comment by aikaterna** [comment]
If you have a different way to describe this that you feel is more intuitive we can talk about it in RJM's channel on the cog server or somewhere else appropriate.
