### ISSUE TITLE
[Sort of Bug] Casino Memberships

### ISSUE THREAD

**Issue by Merp-Me** [Redjumpman/Jumper-Cogs#230]
When setting up a membership, if the credits are set to none, the membership is given to everyone despite not meeting the other requirements. To avoid that, if a requirement is set to none, that requirement shouldn't be a factor when checking eligibility for a membership.

**Comment by aikaterna** [comment]
Imo, this isn't a bug. Every person that has the requirement that you set (more than 0 credits) will get the membership. If you don't want the membership to qualify via credit levels, don't set that option.
