### ISSUE TITLE
[Casino] Role based Memberships not assigning.

### ISSUE THREAD

**Issue by ghost** [Redjumpman/Jumper-Cogs#231]
All of my memberships are based on roles, those with the proper roles do not seem to be assigned the correct membership when running !casino stats

**Comment by aikaterna** [comment]
After looking into this, there are a few conditions that need to be met before membership awarding can occur. 

The user must have interacted with Casino at some point during a game. If they have never played a game, even if they have the appropriate role, they will not have the proper membership nor will it be automatically awarded to them. They can see their wins/losses/stats listed with [p]casino stats. If they are all 0s across the board they will not be counted.

You must have both Casino and Economy in local (server-based) mode and not global. 
[p]bankset showsettings
[p]casino info

If your economy is global you will not be able to switch it to server based without wiping the entire file. Same with Casino, if you need to toggle the mode, it will clear stats for everyone.
