### ISSUE TITLE
[Casino] Membership

### ISSUE THREAD

**Issue by Merp-Me** [Redjumpman/Jumper-Cogs#235]
Membership is no longer automatically assigned to people as they meet the requirement like it did before for example when someone receives a role, they were given the membership within 10min or when someone reached a certain credit threshold.

**Comment by aikaterna** [comment]
Please give https://github.com/Redjumpman/Jumper-Plugins/issues/231#issuecomment-761250920 a read.

**Comment by Merp-Me** [comment]
Both the economy and bank have been set to local and the membership requires a specific role that I have in the server and I have used economy commands multiple times but still haven't been assigned the membership
<img width="216" alt="Screenshot 2021-01-21 at 12 56 41 AM" src="https://user-images.githubusercontent.com/64408204/105259507-d823cb80-5b83-11eb-8712-1bba485df9d6.png">
<img width="494" alt="Screenshot 2021-01-21 at 12 56 14 AM" src="https://user-images.githubusercontent.com/64408204/105259511-d8bc6200-5b83-11eb-87ed-1d2fb53538f9.png">
<img width="411" alt="Screenshot 2021-01-21 at 12 55 20 AM" src="https://user-images.githubusercontent.com/64408204/105259512-d954f880-5b83-11eb-8d02-2faeb9ffd4e0.png">
<img width="542" alt="Screenshot 2021-01-21 at 12 54 27 AM" src="https://user-images.githubusercontent.com/64408204/105259513-d9ed8f00-5b83-11eb-95bb-cad94d5c14eb.png">

**Comment by Majesty01** [comment]
Same problem here

**Comment by XargsUK** [comment]
I'm having a similar issue. I've tried specifying the role name as text, @rolename and the role ID number, all of which do not resolve the issue. 

```
Bank settings:

Bank name: Bank of Pepega
Bank scope: Server
Currency: CyCoins
Default balance: 250
Maximum allowed balance: 9,223,372,036,854,775,807
```

```
Game         Access    Max    Min    Payout  On    CD
---------  --------  -----  -----  --------  ----  ----
Allin             0                          True  30m
Blackjack         0  50000     50       2    True  5s
Coin              0  50000     10       1.5  True  5s
Craps             0  50000     50       2    True  5s
Cups              0  50000     25       1.8  True  5s
Dice              0  50000     25       1.8  True  5s
Double            3  50000     10            True  5s
Hilo              0  50000     25       1.7  True  5s
War               0  50000     25       1.5  True  5s

Casino Name: CyFrogs Casino
Casino Open: True
Global: False
Payout Limit ON: False
Payout Limit: 10000
```

**Comment by aikaterna** [comment]
This should be resolved in https://github.com/Redjumpman/Jumper-Plugins/commit/a37ddc9ce7962f7645b590bbb54f07e887303f5f
