### ISSUE TITLE
[Pokedex] More pokemons?

### ISSUE THREAD

**Issue by ltzmax** [Redjumpman/Jumper-Cogs#236]
So.. there is now [898 Pokemons](https://gist.github.com/simsketch/1a029a8d7fca1e4c142cbfd043a68f19) in the dex, while pokedex cog only have 890, any plans to add the new ones?

**Comment by aikaterna** [comment]
What pokemon are missing? Each entry has to be hand-written and formatted into the data csv for pokedex.

**Comment by ltzmax** [comment]
> What pokemon are missing? 

These are missing:
#891-Kubfu
#892-Urshifu
#893-Zarude
#894-Regieleki
#895-Regidrago
#896-Glastrier
#897-Spectrier
#898-Calyrex

they're Gen 8 pokemons.

**Comment by Redjumpman** [comment]
Added in 3.1.5 #239
