### ISSUE TITLE
[Casino] Double win shows incorrect win amount

### ISSUE THREAD

**Issue by flaree** [Redjumpman/Jumper-Cogs#244]
On winning a double game it appears to show their total balance and not how much they've actually won.
![image](https://user-images.githubusercontent.com/31554168/110187161-2efc0200-7dcc-11eb-9663-7a8db438ff5a.png)

(I'll try look into it, but those classes scare me)

**Comment by aikaterna** [comment]
7664eceb708843befb21218ff8d92464237f49e8
