### ISSUE TITLE
[Shop] Role-specific shop

### ISSUE THREAD

**Issue by Zenchaeus** [Redjumpman/Jumper-Cogs#247]
So the problem is, shops that are supposed to be only available for certain roles can be accessed by other roles thus giving them an option to purchase things from shops where they aren't meant to have access to. It would be great if this could be fixed because this cog is super useful.

**Comment by aikaterna** [comment]
Hi, I did some looking into this and if the user has the administrator perm on the server it bypasses any role restrictions for the shop. When I removed admin perms from my test user and that user also did not have the specific role the shop was locked to, I was not able to buy anything nor view anything in the role-locked shop.
