### ISSUE TITLE
shop stuff

### ISSUE THREAD

**Issue by Steelmaker86** [Redjumpman/Jumper-Cogs#25]
there is a glitch where the bot automatically deletes it's own list message or buy things, so i can't see what is wrong or what i need to do

**Comment by Redjumpman** [comment]
I am confused by what you mean. When you say list message do you mean it deletes items that are in the shop? What commands are you using? Can you walk me through an example of what is causing your issue?

**Comment by Redjumpman** [comment]
I am closing this issue because it has been almost 2 months since you have responded to my follow-up.
