### ISSUE TITLE
[Raffle] a error when i run the bot or reload the cog.

### ISSUE THREAD

**Issue by kpopdev** [Redjumpman/Jumper-Cogs#253]
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]: [2021-08-15 22:23:45] [ERROR] red.jumper-plugins.raffle: Error in raffle_worker task.
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]: Traceback (most recent call last):
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/raffle/raffle.py", line 373, in raffle_worker
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:     await self.raffle_teardown(guild, raffles[key]["ID"])
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/raffle/raffle.py", line 421, in raffle_teardown
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:     await self.pick_winner(guild, channel, msg)
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/raffle/raffle.py", line 441, in pick_winner
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:     valid_entries = await self.validate_entries(users, msg)
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/raffle/raffle.py", line 452, in validate_entries
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]:     dos, roles, timestamp = msg.embeds[0].fields
Aug 15 22:23:45 vmi538808.contaboserver.net python[31301]: ValueError: not enough values to unpack (expected 3, got 2)

**Comment by aikaterna** [comment]
Try https://github.com/Redjumpman/Jumper-Plugins/commit/85988bad21c0b820effa61f8bf15b37f5f562cfa and that should work for you on this issue.
