### ISSUE TITLE
[raffle] Error in raffle_worker task.

### ISSUE THREAD

**Issue by kpopdev** [Redjumpman/Jumper-Cogs#254]
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]: [2021-09-04 00:12:30] [ERROR] red.jumper-plugins.raffle: Error in raffle_worker task.
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]: Traceback (most recent call last):
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/raffle/raffle.py", line 373, in raffle_worker
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]:     await self.raffle_teardown(guild, raffles[key]["ID"])
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/raffle/raffle.py", line 421, in raffle_teardown
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]:     await self.pick_winner(guild, channel, msg)
Sep 04 00:12:30 vmi538808.contaboserver.net python[22433]: UnboundLocalError: local variable 'msg' referenced before assignment

**Comment by aikaterna** [comment]
Try https://github.com/Redjumpman/Jumper-Plugins/commit/9281bba0689cb3eb8d45080c2e3edf9f456601ae.
