### ISSUE TITLE
casino.py: correct spelling of "recieved" to "received"

### ISSUE THREAD

**Issue by Annihilator6000** [Redjumpman/Jumper-Cogs#27]
QoL spelling issue.

http://i.imgur.com/ufcxnv3.jpg

http://i.imgur.com/z3k0NNH.jpg

There are 5 instances of this in casino.py.

Edit: There are 2 instances of this for "recieved" and 3 for "recieve"

**Comment by Redjumpman** [comment]
Thanks for pointing this out. I just added this to the next update. I'll close this issue once I update this weekend.

**Comment by Redjumpman** [comment]
Fixed in patch 1.5.9
