### ISSUE TITLE
Using store cog, unable to use command Store

### ISSUE THREAD

**Issue by BlackCowThrower** [Redjumpman/Jumper-Cogs#3]
Running the store command creates an error in the console.
TypeError: string indices must be integers.
Im afraid that I'am not much more use than this,
Thanks

https://i.gyazo.com/thumb/1200/_305116b5078a11d2b4785467d2ff1767-png.jpg

**Comment by Redjumpman** [comment]
Send me a msg on Discord. Redjumpman#2375.
