### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by PhanxD** [Redjumpman/Jumper-Cogs#32]
Deleting or settings IDs "on ice" if a person leave the Discord.
Currently the command [p]steal will not work, until you delete the person who left, out of the "database"

**Comment by Redjumpman** [comment]
I'll try to take a look at fixing that soon. Thanks for letting me know.

**Comment by skeith** [comment]
I reported this long ago to you @Redjumpman via DM.

**Comment by Redjumpman** [comment]
I think I remember you telling me about it, but I don't have to have a good memory if there is an issue posted for it.

**Comment by Redjumpman** [comment]
This is fixed as of the new patch for Cookie. Please post a new issue if it is still occurring.
