### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by PhanxD** [Redjumpman/Jumper-Cogs#34]
Sorry to bother you with cookie again ^^
If you give a cookie to a person, who has no account, the person will still loose the cookies, but no one will get them. So they get deleted.
Is a nice troll-function to delete all the cookies while annoying the others.

**Comment by Mamalus** [comment]
Update your cookie.
I added a check to give out cookie if the user has no account on it.

**Comment by Redjumpman** [comment]
@PhanxD Update your cookie and please post back if the issue is resolved. This issue will close COB 1600 EST unless you reply that the problem still exists.

**Comment by PhanxD** [comment]
Thank you, didn't knew there was an update. Its fixed :)
