### ISSUE TITLE
Membership Creation progress doesn't work (casino cog)

### ISSUE THREAD

**Issue by Testdude3234** [Redjumpman/Jumper-Cogs#38]
TypeError: string indices must be integers
      File "discord/ext/commands/core.py", line 50, in wrapped
        ret = yield from coro(*args, **kwargs)
      File "/home/genisyn/Red-DiscordBot/cogs/casino.py", line 1137, in _createmembership_casino
        if int(access.content) in [x["Access"] for x in list(settings["Memberships"])]:
      File "/home/genisyn/Red-DiscordBot/cogs/casino.py", line 1137, in <listcomp>
        if int(access.content) in [x["Access"] for x in list(settings["Memberships"])]:
    
    Exception in command 'casino createmembership'

When doing this
https://cdn.discordapp.com/attachments/240302038565519361/288672329347891210/dfdf.JPG

**Comment by Redjumpman** [comment]
I have this issue fixed, but I'm waiting to polish out some more changes before I push.

**Comment by Redjumpman** [comment]
Fixed in patch: b8a3194
