### ISSUE TITLE
Casino Wipe not working regardless of server name

### ISSUE THREAD

**Issue by Testdude3234** [Redjumpman/Jumper-Cogs#39]
AttributeError: 'NoneType' object has no attribute 'name'
      File "discord/ext/commands/core.py", line 50, in wrapped
        ret = yield from coro(*args, **kwargs)
      File "/home/genisyn/Red-DiscordBot/cogs/casino.py", line 1293, in _wipe_casino
        server = [self.bot.get_server(x) for x in servers
      File "/home/genisyn/Red-DiscordBot/cogs/casino.py", line 1294, in <listcomp>
        if self.bot.get_server(x).name == servername][0]
    
    Exception in command 'casino wipe'

Tried to wipe the casino on 3 servers and spelled them right and made sure and this error comes up
Error in command 'casino wipe' - AttributeError: 'NoneType' object has no attribute 'name'

Also if you can, maybe polish up the existing error messages like
Error in command 'blackjack' - KeyError: 'Access Level'

**Comment by Redjumpman** [comment]
I am assuming this is fixed since you finally figured out how to update your casino, so I'm closing this issue.
