### ISSUE TITLE
Shop cog suggestions

### ISSUE THREAD

**Issue by Mamalus** [Redjumpman/Jumper-Cogs#40]
Can you make an alert for server owner and admin to get notified in dm when they redeem their item?

For roles is it possible to make a temporary role for certain amount of days that can be kept. (Almost like a VIP area)

**Comment by Redjumpman** [comment]
There is already a feature that does this. If you need to first set a role with >setshop role . The role should be something already on your server, IE admin. Then use the command >setshop notify which will turn the notifications on. It will send a DM to every person with that role, any time someone redeems an item.

![image](https://cloud.githubusercontent.com/assets/18455011/24304790/a9ace06a-1088-11e7-9a0c-013793ae22ec.png)
