### ISSUE TITLE
casino bug

### ISSUE THREAD

**Issue by vptyyppi1** [Redjumpman/Jumper-Cogs#41]
When I use [p]casino info, I get this: "Error in command 'casino info' - HTTPException: BAD REQUEST (status code: 400)". I'm a noob at this stuff, so I'm not able to solve this myself. The command worked fine before. Any help will be appreciated! 😃

**Comment by Redjumpman** [comment]
Please provide the following information with your issue:

**Casino version:** (type [p]casino version)

**What occurred right before this bug?** (Or has the bug always been happening)

**Try running the command [p]casino forceupdate**

Screenshot of the error in your command window (Black box)

**Comment by vptyyppi1** [comment]
I was running an old version, so [p]casino version didn't even work. Now that I uninstalled the cog properly and downloaded the newest version (1.6.5), the error changed from "Error in command 'casino info' - HTTPException: BAD REQUEST (status code: 400)" to "Error in command 'casino info' - KeyError: 'Memberships'". Screenshot of the new error here: https://mylly.s-ul.eu/7Uw20pQF

**Comment by Redjumpman** [comment]
Download the update I just pushed for 1.6.6. Then run the command [p]casino forceupdate this will update your JSON so it should function properly.

**Comment by vptyyppi1** [comment]
And here we go again: "Error in command 'casino info' - HTTPException: BAD REQUEST (status code: 400)"...
Screenshot: https://mylly.s-ul.eu/aptv7fRh

**Comment by Redjumpman** [comment]
When you have time, please send me a DM on discord. I'll send you a casino file to try and diagnose the issue. I'm having a hard time replicating your bug. This usually happens when the msg is over the 2000 character limit, but I don't know how that is possible, unless all of your games have min/max bets of 9^38, but even then I'm not sure. Might need to see your JSON file as well.

**Comment by vptyyppi1** [comment]
I'll check my max bets, there are some pretty damn high numbers there. I'll tell you if changing them works

**Comment by vptyyppi1** [comment]
Hey, it worked! My coin game's max bet was the cause, thank you so much! 😄

**Comment by Redjumpman** [comment]
Awesome. Have fun 👍

**Comment by vptyyppi1** [comment]
I'll ask this here, how can I set the max bet to none, just like Allin?
