### ISSUE TITLE
Heist doesn't update the info, also another issue.

### ISSUE THREAD

**Issue by iiCarelessness** [Redjumpman/Jumper-Cogs#49]
http://i.imgur.com/XqHnxlO.png

This one shows that, after I set a variable, it doesn't update it in the info.

http://i.imgur.com/4lx2NoN.png

This one shows that, even trying to do !heist play while you were jailed, it shows your jail time is non-existent and tells you to !heist release, upon doing so, you're told you have more jail time?

**Comment by Redjumpman** [comment]
I'll be working to fix these issues. Please in the future if you have multiple bugs make a separate issue for each one so I can reference each when I commit.

**Comment by Redjumpman** [comment]
If the second bug isn't fixed, please post a second issue after trying Update 2.2.15.
