### ISSUE TITLE
Maximum on chips saved?

### ISSUE THREAD

**Issue by Kyrislian** [Redjumpman/Jumper-Cogs#59]
Would it be possible to place a limit on how many chips can be saved/converted before having to cash them out into credits? Am having users who are hitting over 1m chips XD

**Comment by Redjumpman** [comment]
I think that the best way to manage this is to have lower max bets on your games. The defaults are not balanced in any way. I also have the threshold system which should allow you to limit really large payouts as well. You can learn more about thresholds here: https://github.com/Redjumpman/Jumper-Cogs/wiki/Casino#threshold . I'm also considering adding an optional conversion fee for exchanging chips or credits. Based on issue #29 .
