### ISSUE TITLE
Issue with buymsg In shop items

### ISSUE THREAD

**Issue by ThePheonixGuy** [Redjumpman/Jumper-Cogs#61]
Any shop item that has infinite quantity reaches this error when trying to set a buymsg:

Error in command 'setshop buymsg' - ValueError: invalid literal for int() with base 10: '∞'

**Comment by Redjumpman** [comment]
I have the bug documented, will be fixed in the rewrite.

**Comment by Redjumpman** [comment]
Fixed in Patch 2.2.8 commit 0a34777
