### ISSUE TITLE
Colored Items in Shop [Feature Request]

### ISSUE THREAD

**Issue by OlexaKid64** [Redjumpman/Jumper-Cogs#62]
As I think ahead to the shop update, it would be pretty cool to have color coordinates items in the shop. Since I really really hope you implement the random item function for the shop, it would be cool to have different colored items to be different tiered items. It would also just be pretty :) Not sure how hard that is to code though.

**Comment by Redjumpman** [comment]
Text coloring is not something that is supported by Discord. The way text can be currently colored, is through markdown's syntax highlighting. This method will only highlight certain words based on the programming language selected. While I would love to be able to color text in discord, it is currently not possible with the current iteration. For that reason, I'll be closing this issue.
