### ISSUE TITLE
Adding the "split" mechanic to Blackjack

### ISSUE THREAD

**Issue by vagax** [Redjumpman/Jumper-Cogs#63]
My users occasionally try to use the split command which of course isn't yet integrated into the casino module, so my feature question is if Split can be added

**Comment by Redjumpman** [comment]
When you say split, I assume you mean for blackjack. Split has been something that I have considered adding, but doing so would require me to rewrite the blackjack logic. Once I complete some other pending tasks, I'll come back to this issue, and see what can be done.

**Comment by vagax** [comment]
Oh yeah sorry, i meant Blackjack.

**Comment by Redjumpman** [comment]
Split adds a lot of extra complexity to blackjack atm. Blackjack for my cog is meant to be fairly simple, and while it mirrors real blackjack it should not be viewed as a stand in replacement. I do appreciate the idea, but at this time, I won't be considering it for V3.
