### ISSUE TITLE
Unable to transfer casino credits.

### ISSUE THREAD

**Issue by vagax** [Redjumpman/Jumper-Cogs#64]
Users are unable to transfer credits using !casino transfer [user] [credits]. It always generates a error which goes like this:

> [11/05/2017 13:41] ERROR red on_command_error 369: Exception in command 'casino transfer'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Vagax\Documents\MarekBot 2\cogs\casino.py", line 553, in _transfer_casino
    cooldown = self.check_cooldowns(user, "Transfer", settings)
  File "C:\Users\Vagax\Documents\MarekBot 2\cogs\casino.py", line 2362, in check_cooldowns
    user_time = settings["Players"][user.id]["Cooldowns"][method]
KeyError: 'Transfer'

I have made no core changes, only thing i changed were a few multiplier, casino name and the name of credits.

**Comment by Redjumpman** [comment]
What version of casino are you currently using? Check using the >casino version command

**Comment by vagax** [comment]
Here you go
"You are currently running Casino version 1.7.07."

**Comment by Redjumpman** [comment]
Based on our discord discussion, using the forceupdate command fixed this problem. As a result I am closing this issue.
