### ISSUE TITLE
[Shop/Feature Request] - Restrict items by role

### ISSUE THREAD

**Issue by batboy710** [Redjumpman/Jumper-Cogs#77]
The Ability To Lock Certain Items To Certain Roles

**Comment by Redjumpman** [comment]
Do you mean only certain roles can purchase? Or only certain roles can redeem an item?

**Comment by batboy710** [comment]
for example:
a shop for everyone and another shop for members with an "elite" role and
another one for members with x role.

**Comment by Redjumpman** [comment]
I'm not sure if I would add sub shops. It is more likely that it would be if you had role X then you would see additional items in the normal shop list. I'll have to think about this implementation some more. Anyone else reading this feel free to throw your $0.02 in. All in all, if this would added it would be completely optional thing.

**Comment by batboy710** [comment]
Yeah it's basically the same thing, new items show up if you have x role,
also can u send the link to send the 0.02$?

**Comment by Redjumpman** [comment]
My paypal is on the main page if you want to throw two coppers into the wishing well friend.

**Comment by Redjumpman** [comment]
Added to the roadmap for a future V3 update to shop.

**Comment by Redjumpman** [comment]
Instead of having certain items show up, I plan to have only certain shops show up. Since with the shop Rewrite for V3 you can have multiple shops. This will also have the side-effect of a slightly slimmer data file as well. Everyone please feel free to comment on this if you have other ideas or concerns.
