### ISSUE TITLE
Bug in Casino: blackjack

### ISSUE THREAD

**Issue by Nyefan** [Redjumpman/Jumper-Cogs#8]
Occasionally, player(self, args) on line 677 in the casino cog fails without raising an error, resulting in an empty player hand and a dealer victory.

On a marginally related note, I'd suggest making "stay" the default behavior if they timeout for line 635.

**Comment by Redjumpman** [comment]
That's an interesting error. I will do some testing to try and track down why that issue happens. If you can determine how I can replicate that bug please let me know. Also, using stay for the default timeout is a good idea, and I will implement that in the next release.

**Comment by Redjumpman** [comment]
The latest update makes the default as stay, and it should resolve most of the handling errors. May still encounter an error if be spammed repeatedly on a per user basis. Will close this if no further issues in the next week.

**Comment by Redjumpman** [comment]
This error appears to be fixed with recent changes. Try updating to the latest patch. Start a new issue if you encounter a bug or error.
