### ISSUE TITLE
Ideas for shop cog

### ISSUE THREAD

**Issue by CreatorVilius** [Redjumpman/Jumper-Cogs#82]
My wish list what should be added:

> `[p]inventory equip (Role)`

-people could make their own shop(Items would be taken from inventory, but hey, atleast you get the money ¯\_(ツ)_/¯ .
> `[p]usershop` `[p]setusershop`

**Comment by Redjumpman** [comment]
Shop uses role token as a one-time use role. being able to equip/unequip roles is an entirely different system outside the scope of shop. There are too many factors to consider and monitor. This is possibly something that could be added to shop through hooks if another developer made this.

I'm not really a fan of people making their own items. It doesn't really make sense to just have a bunch of random crap on the shop with no use. A normal user doesn't really have the power/ability to assign a real value to an item. Additionally, I would need to track who is buying and selling. It's a huge headache with a really niche value. I have considered creating an AH plugin for shop, but that's far down the pipeline after I complete some other stuff  in my roadmap.
