### ISSUE TITLE
[Casino] [Bug] Aces not counting right in some circumstances

### ISSUE THREAD

**Issue by zephyrkul** [Redjumpman/Jumper-Cogs#83]
Copying this from a message someone sent to me:
> In blackjack, any ace should count 11 unless you are bust, in which case it counts 1. That works fine for an initial ace, but not once you hit. For example, in the below I should score 19 and win, but the bot counts it as 9 and a loss.
> 
> Your hand: Ace, Ace, Ace, 6
> Your score: 9
> Dealer's hand: 10, 7
> Dealer's score: 17
> ======House Wins!======

**Comment by Redjumpman** [comment]
I will take a look at this. You definitely should have had a soft 19 there. I'll reference this issue with a patch when I can fix it. Thanks for the report.

**Comment by Redjumpman** [comment]
Fixed in Patch 1.7.17

**Comment by zephyrkul** [comment]
Thank you very much :)
