### ISSUE TITLE
[Bug/Raffle] Error raised on purchase without bank account

### ISSUE THREAD

**Issue by Ruined1** [Redjumpman/Jumper-Cogs#96]
# I'm submitting a ...
- [x] bug report
- [ ] feature request
- [ ] support request

# **Cog Information**

Name:  Raffle
Version: No versioning available, but freshly installed brand new.

# Bug Report
**Screenshot of console: (If Applicable)**
```
[23/01/2018 21:54] ERROR red on_command_error 369: Exception in command 'raffle
buy'
Traceback (most recent call last):
  File "/servers/redbot/cogs/economy.py", line 256, in _get_account
    return deepcopy(self.accounts[server.id][user.id])
KeyError: '133040031899058176'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/servers/redbot/cogs/raffle.py", line 81, in buy
    elif not bank.can_spend(user, credits):
  File "/servers/redbot/cogs/economy.py", line 193, in can_spend
    account = self._get_account(user)
  File "/servers/redbot/cogs/economy.py", line 258, in _get_account
    raise NoAccount()
cogs.economy.NoAccount
Task exception was never retrieved
```

**Command used:**
.raffle buy 10

**Expected result:**
purchase 10 tickets

**Actual Results**
Tickets were not purchase and above error was incurred.
AFTER having user .bank register, everything worked perfectly.

**Steps to reproduce:**
Have a user without a registered bank try to buy raffle tickets

**Please tell me about your environment/OS:**
Red Discord Bot - Ubuntu
Client in Question - Windows

**Comment by Ruined1** [comment]
Also, the raffle didn't pay out the winner.

**Comment by skeith** [comment]
This such issue also occurred on other Redjumpman cogs and have been reported previously. Some of them already have a proper error handling, so I guess Redjumpman forgot about this one.

**Comment by Ruined1** [comment]
@skeith yes, I did notice that other cogs had the check, I figured it was just an oversight. I'm also worried that the raffle completed successfully, but did not actually pay the winner.

**Comment by Redjumpman** [comment]
Also, raffle just sucks. It has a lot of legacy code that just hasn't ever been touched. With that said, I'll put some band-aids on it tonight, until I can do an honest refactor for v3.

**Comment by Redjumpman** [comment]
Oh... The problem with winning credits... is that raffle was never intended to award people with credits. Tickets are bought with credits, but the prize is supposed to be something the admin has created on the server. I'll update the doc strings to clarify. If you all would like the option of a [cash raffle](https://en.wikipedia.org/wiki/Raffle#Cash_raffle) consider making a separate issue as a feature request for v3.

**Comment by Redjumpman** [comment]
This is now fixed in the latest [commit](https://github.com/Redjumpman/Jumper-Cogs/commit/c6bfaa0fd5dda3deec1dd066310dae98a68e1a18)
